from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for, abort, flash
from flask_login import current_user, login_required
from app.extensions import db
from app.models import AboutPage
from flask import session

bp = Blueprint("about", __name__)

def _is_admin() -> bool:
    # Your login flow stashes admin_id in the session on success
    # (see auth.login_api). If present, treat as admin.
    return bool(session.get("admin_id"))

@bp.get("/about")
def about_page():
    # show most-recent (by UpdatedAt or CreatedAt fallback) – same intent as original
    row = (
        db.session.query(AboutPage)
        .order_by(AboutPage.ReleaseDate.desc(),
                db.func.coalesce(AboutPage.UpdatedAt, AboutPage.CreatedAt).desc())
        .first()
    )
    return render_template("about.html", row=row, is_admin=_is_admin())

@bp.get("/about/history")
def about_history():
    rows = (
        db.session.query(AboutPage)
        .order_by(AboutPage.ReleaseDate.desc(),
                  db.func.coalesce(AboutPage.UpdatedAt, AboutPage.CreatedAt).desc())
        .all()
    )
    return render_template("about_history.html", rows=rows, is_admin=_is_admin())


@bp.route("/about/releases/new", methods=["GET", "POST"])
@login_required
def about_new_release():
    if not _is_admin():
        abort(403)

    if request.method == "POST":
        team = request.form.get("TeamNumber", "").strip()
        version = request.form.get("VersionNumber", "").strip()
        date_str = request.form.get("ReleaseDate", "").strip()
        name = request.form.get("ProductName", "").strip()
        desc = request.form.get("ProductDescription", "").strip()

        if not (team and version and date_str and name and desc):
            flash("All fields are required.", "danger")
            return redirect(url_for("about.about_new_release"))

        try:
            rd = datetime.strptime(date_str, "%Y-%m-%d").date()
        except ValueError:
            flash("Release Date must be YYYY-MM-DD.", "danger")
            return redirect(url_for("about.about_new_release"))

        row = AboutPage(
            # AboutPageID will be auto-generated by the model default
            TeamNumber=team,
            VersionNumber=version,
            ReleaseDate=rd,
            ProductName=name,
            ProductDescription=desc,
            CreatedAt=datetime.utcnow(),
            UpdatedAt=datetime.utcnow(),
        )
        db.session.add(row)
        db.session.commit()
        flash("New About release created.", "success")
        return redirect(url_for("about.about_history"))

    return render_template("about_edit.html", mode="create", row=None)

@bp.route("/about/releases/<string:about_id>/edit", methods=["GET", "POST"])
@login_required
def about_edit_release(about_id: str):
    if not _is_admin():
        abort(403)

    row = (
        db.session.query(AboutPage)
        .filter(AboutPage.AboutPageID == about_id)
        .first()
    )

    if not row:
        flash("Release not found.", "danger")
        return redirect(url_for("about.about_history"))

    if request.method == "POST":
        team = request.form.get("TeamNumber", "").strip()
        version = request.form.get("VersionNumber", "").strip()
        date_str = request.form.get("ReleaseDate", "").strip()
        name = request.form.get("ProductName", "").strip()
        desc = request.form.get("ProductDescription", "").strip()

        if not (team and version and date_str and name and desc):
            flash("All fields are required.", "danger")
            return redirect(url_for("about.about_edit_release", about_id=about_id))

        try:
            rd = datetime.strptime(date_str, "%Y-%m-%d").date()
        except ValueError:
            flash("Release Date must be YYYY-MM-DD.", "danger")
            return redirect(url_for("about.about_edit_release", about_id=about_id))

        row.TeamNumber = team
        row.VersionNumber = version
        row.ReleaseDate = rd
        row.ProductName = name
        row.ProductDescription = desc
        row.UpdatedAt = datetime.utcnow()

        db.session.commit()
        flash("Release updated.", "success")
        return redirect(url_for("about.about_history"))

    return render_template("about_edit.html", mode="edit", row=row)


@bp.post("/about/releases/<string:about_id>/delete")
@login_required
def about_delete_release(about_id: str):
    if not _is_admin():
        abort(403)

    row = (
        db.session.query(AboutPage)
        .filter(AboutPage.AboutPageID == about_id)
        .first()
    )

    if not row:
        flash("Release not found.", "danger")
        return redirect(url_for("about.about_history"))

    db.session.delete(row)
    db.session.commit()
    flash("Release deleted.", "success")
    return redirect(url_for("about.about_history"))